"""Fix: unique contraints v2

Revision ID: 120d7891cfe2
Revises: cf42f4a20070
Create Date: 2026-05-19 19:04:28.060535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120d7891cfe2'
down_revision: Union[str, Sequence[str], None] = 'cf42f4a20070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_oauth_subject_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_oauth_subject_id_key'), 'users', ['oauth_subject_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
