"""fix: users table column age from string to int, listins.id added a default value

Revision ID: a7c2f2e3824e
Revises: 6fa01d843d1d
Create Date: 2026-05-19 18:07:54.033036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c2f2e3824e'
down_revision: Union[str, Sequence[str], None] = '6fa01d843d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=False))
    op.alter_column('users', 'age',
                existing_type=sa.VARCHAR(),
                type_=sa.Integer(),
                postgresql_using="age::integer",
                existing_nullable=False)
    op.create_unique_constraint("uq_users_oauth_provider", 'users', ['oauth_provider'])
    op.drop_column('users', 'oauth_provide')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provide', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint("uq_users_oauth_provider", 'users', type_='unique')
    op.alter_column('users', 'age',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
