"""Fix: unique contraints

Revision ID: cf42f4a20070
Revises: a7c2f2e3824e
Create Date: 2026-05-19 19:02:27.172435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf42f4a20070'
down_revision: Union[str, Sequence[str], None] = 'a7c2f2e3824e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_oauth_provider'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_oauth_identity', 'users', ['oauth_provider', 'oauth_subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_oauth_identity', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_oauth_provider'), 'users', ['oauth_provider'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
